### ISSUE TITLE
Different font and font size in ToC and cross-references

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#125]
Different font is used in Table of Contents and in cross-references. 

Original (from ITU-T Editing Guidelines):
![image](https://user-images.githubusercontent.com/55683568/68091224-590e7e80-fe7d-11e9-8189-e2ee707b7be8.png)

Rendered:
![image](https://user-images.githubusercontent.com/55683568/68091228-63c91380-fe7d-11e9-88dd-6f1781402aa0.png)

Font size of cross-references and URLs should be bigger.
![image](https://user-images.githubusercontent.com/55683568/68091254-9d9a1a00-fe7d-11e9-9f31-de06281bbd25.png)
![image](https://user-images.githubusercontent.com/55683568/68091894-c8886c00-fe85-11e9-803e-e6ed254df4ab.png)

**Comment by ronaldtse** [comment]
ITU has indicated that:
- All fonts are Times New Roman size 12.
- Supplementary text like Notes and Examples are size 11.

**Comment by opoudjis** [comment]
Crossreferences font has been resolved in: https://github.com/metanorma/mn-samples-itu/issues/32

**Comment by opoudjis** [comment]
ToC font is because ToCs in Metanorma are hyperlinked, and ITU has decided that hyperlinks should be in a different font. Removing hyperlinks.

**Comment by opoudjis** [comment]
Not working. And since ITU appear to be creating tables of contents MANUALLY, they are dodging an issue of their own creating: their requirement for a different font for hyperlinks is inevitably going to affect tables of contents. The hyperlinks are inserted automatically by Word, so this issue cannot be avoided: I may well instead have to insert styling for hyperlinks outside of Word CSS, given the havoc it has created.

Again, ITU have created havoc for hyperlink rendering (it also has affected cross references), with their stylesheet requirement for a different font and font size for (all) hyperlinks, and they are avoiding the issue by extensive manual editing of documents. (The manual Tables of Contents now make sense.) This is not acceptable under Metanorma.

**Comment by ronaldtse** [comment]
@opoudjia It’s time to stop blaming the SDOs, this is just unhealthy to us and offensive to them. 

Word can render ToC in a different style. The ToC at ITU is not, despite your assertion, manually rendered.

**Comment by opoudjis** [comment]
Hyperlinks have to be styled outside the stylesheet: the sample documents do not set hyperlinks to Arial as a stylesheet style, which is why they don't have this issue. In Word output, I am setting only explicit hyperlinks (`<link>`) to be rendered with CSS class "url", and only `a.url` is defined to be in Arial. That means I can make cross references hyperlinks again, rescinding https://github.com/metanorma/mn-samples-itu/issues/32
