### ISSUE TITLE
Formatting only one part of the URL

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#128]
Is there an option to make only one part of the URL italic or bold, without breaking the URL?

Original (from ITU-T Editing Guidelines):
![image](https://user-images.githubusercontent.com/55683568/68091710-63cc1200-fe83-11e9-9ad4-18c7e27cf1c9.png)

Rendered:
![image](https://user-images.githubusercontent.com/55683568/68091703-47c87080-fe83-11e9-9970-baabdd9c495c.png)

[url.zip](https://github.com/metanorma/metanorma-itu/files/3802109/url.zip)

**Comment by opoudjis** [comment]
Yes:

````
http://www.example.com[`http://example.**com**`]
````

The link itself obviously cannot be formatted; the link text can, and nothing prevents it being typewriter font with bold and italic. So in this instance,

````
http://www.itu.int/xml-namespace/itu-t/x.nnn.pp/[`http://www.itu.int/xml-namespace/itu-t/x.**__nnn.pp__**/`]
````

... Note though that this isn't in reality meant to link to anything at all, since the link target does not exist. So all you really need is just:

````
`\http://www.itu.int/xml-namespace/itu-t/x.**__nnn__**.pp/`
````

The backslash, as described in https://asciidoctor.org/docs/user-manual/#url, prevents the URL from being parsed as a URL, and leaves it as text.
