### ISSUE TITLE
Generating +- symbol using stem expression

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#226]
After updating asciimath gem, ± symbol cannot be generated using `+-` syntax, rather only using `pm` syntax. Since this is not in accordance to what is written in http://asciimath.org/ for ± symbol, I would like to check whether this is fine. In case this change should have been applied, we would need to check converted documents to make the changes accordingly.

Generation of ± symbol using syntax `a small amount, e.g. stem:[+-1], or more rarely by stem:[+-2]`:

![image](https://user-images.githubusercontent.com/55683568/87256325-bbe6f980-c491-11ea-8aff-04d35b0c45cf.png)

Generation of ± symbol using syntax `a small amount, e.g. stem:[pm1], or more rarely by stem:[pm2]`:

![image](https://user-images.githubusercontent.com/55683568/87256343-e8027a80-c491-11ea-8a97-6395b2ef776c.png)

**Comment by opoudjis** [comment]
@anermina, this seems to be a more complicated issue. 

`a small amount, e.g. stem:[+-1], or more rarely` converts successfully to: `<p id="_29e9d3ed-5ea6-48ac-ac56-19c6b3e5786d">a small amount, e.g. <stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><mo>±</mo><mn>1</mn></math></stem>, or more rarely</p>`

The given example `a small amount, e.g. stem:[+-1], or more rarely by stem:[+-2]` gives the results you find.

**Comment by opoudjis** [comment]
That STEM phrase is being parsed as `-1], or more rarely by stem:[-2` —which means that stuff inside of pluses is being extracted as the mathematical expression, with `-2` being tacked on.

It turns out that pluses are used to quote passthrough expressions in Asciidoctor: https://asciidoctor.org/docs/user-manual/#escaping-unconstrained-quotes . So the detection of `+...+` as a passthrough quotation is taking precedence over the `stem:[...]` bracketing. This is an Asciidoctor parsing issue, which is going to happen when `+...+` happens in a paragraph.

There is in fact a very simple solution: escaping the first plus instance with a backslash:

`a small amount, e.g. stem:[\+-1] or more rarely by stem:[+-2]`
