### ISSUE TITLE
ITU-WHO Focus Group on AI for Health: Box elements

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#333]
ITU-WHO Focus Group on AI for Health deliverables introduced Box element, which can be generated as a table with one cell, but it cannot be named "Box <number>" instead of "Table <number>".

![image](https://user-images.githubusercontent.com/55683568/196006334-1b19a161-0a98-405a-b0f4-4523b033b5d9.png)

Should we introduce Boxes in Metanorma and add a document identifier such as `:toc-boxes:` in order to be able to generate the list of boxes in the ToC?

![image](https://user-images.githubusercontent.com/55683568/196006319-4ccd0bd9-7f6d-4db8-a5d2-5016607f55ce.png)

**Comment by ronaldtse** [comment]
This is interesting, in UN docs they have the same Box element. @opoudjis can we generalize the Box across flavors?

The WHO is a UN body, so it probably adopts similar styles with UN.

**Comment by opoudjis** [comment]
No, because "box" is not a semantic category. All such text which interrupts normal text flow, we have coded as admonitions, and we have done that in the UN as well, we have not introduced a new block. (In fact, metanorma-un treats all admonitions as boxes currently.)

I'm going to have to hear an overwhelming argument against coding these as admonitions. You could argue for sidebar, included in Asciidoctor, as a distinct thing from admonition, because they're not part of the normal text flow, but I don't think that holds; cautions are arguably outside normal text flow too.

Putting boxes into tables of content is self-indulgence. If these were well-thought out semantic components, they wouldn't be being described graphically as boxes to begin with.

At most, a new type of admonition of type sidebar. At most.

**Comment by ronaldtse** [comment]
The point is not whether the Box here is an admonition or a separate element. Semantically it is just an attached element to the text flow and serves the same purpose of an aside/sidebar that is arguably less attached than a NOTE, and can contain notes and examples itself.  

The functional requirement is that:
- the Box is a document-wide numbered element
- we need a list of Boxes in the TOC

**Comment by opoudjis** [comment]
Fine, that's an implementation task. I am inclined to make "box" an admonition type throughout Metanorma, but it is different from "caution" etc.

**Comment by ronaldtse** [comment]
Bringing in @bquast who originally requested this document:

The ITU-WHO Focus Group document (https://github.com/metanorma/mn-samples-itu/pull/156) includes the document element of "Box", which is not used by ITU (i.e. not defined in the "Author's guide for drafting ITU-T Recommendations").

I believe the cause is that the Box is a typical UN doc element, and that this document was co-authored by WHO, hence they have brought the Box element into this document.

@bquast could you help confirm (with Anibal?) whether this Box element is to be supported? Thanks!

**Comment by bquast** [comment]
I'm checking with Anibal and Simao now

**Comment by opoudjis** [comment]
@bquast Any update on this issue?

**Comment by bquast** [comment]
Sorry yes (some time ago, forgot to post it here)

> Yes, indeed. The Author’s Guide for drafting ITU-T Recommendations does not consider ‘boxes’. As reports are not normative, they can contain boxes if required by the author. However, the boxes would need to be edited out if the report happens to become a Supplement or a Recommendation.

**Comment by ronaldtse** [comment]
Thank you @bquast for the clarification.

@opoudjis should we go ahead with your suggestion:
> I am inclined to make "box" an admonition type throughout Metanorma, but it is different from "caution" etc.

?

**Comment by opoudjis** [comment]
Numbering boxes like notes and examples, per clause.
