### ISSUE TITLE
Generating "Editors" in ITU-WHO T-FG AI4H

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#336]
ITU-WHO T-FG-AI4H document adds "Editors" between the "Change log" and "Acknowledgements" sections in the preface. These document attributes aren't being generated in the output HTML/DOC files.

Markup:
````
:fullname: Andreas Reis
:affiliation: World Health Organization
:role: editor
:email: reisa@who.int
:fullname_2: Sameer Pujari
:affiliation_2: World Health Organization
:role_2: editor
:email_2: pujaris@who.int
````

Original document:
![image](https://user-images.githubusercontent.com/55683568/196051888-29eba694-8058-4df8-8888-24829189c520.png)

**Comment by opoudjis** [comment]
This requests a new feature that has never been seen in ITU; it instead has been seen in OGC, as its submitters section.

Moreover, there is no fixed point defined for it to be inserted: neither the change log nor acknowledgements occur in all or indeed most ITU documents.

And I have no assurance that this actually should be inserted into ITU documents in general, or that this specific document is representative of ITU practice.

In short, this is a feature I would decline to implement without more thorough analysis or engagement from ITU. I will certainly reject any notion of inserting the proposed section "like, wherever": this needs to be defined properly, and I simply have zero indication that it has been.

(Which means, if ITU *ever* complain about where Metanorma inserts a feature they have not documented in their editorial guide, the onus is on them to tell us where to insert it. I am not a mind-reader.)

I'm going to do this anyway, despite some profound misgivings, because we can always switch it off by not including contributors in the document header. But you get no choice on where it is inserted: that's the price you pay for asking it to be automatically inserted. It goes before acknowledgements if present, else final clause in preface.

**Comment by opoudjis** [comment]
Generalise extraction of personal names from contributors to include formatted initials.

**Comment by opoudjis** [comment]
For Spanish, providing masc, fem, and nb versions of "editor", but (for now at least) Metanorma is going to pick the masculine default: there's no mechnanism to establish the gender of editors.
