### ISSUE TITLE
"<" and ">" are not rendering

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-itu#37]
These characters are not rendering when the bibliography environment along with appendix environment is present. (Whether you remove the bibliography or appendix environment, the issue get fixed.)

I attach sample file for demonstration:
[lg-issue.zip](https://github.com/metanorma/metanorma-itu/files/3691018/lg-issue.zip)

**Comment by opoudjis** [comment]
What's distressing here is that the XML input is correct: `<stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>V</mi><mo>&lt;</mo><mi>a</mi></math></stem>`. Behaviour is as @manuel489  described: when I remove `[appendix]` markup, `&lt;` is stripped out in the MathML passed on to the HTML, but is retained in the XML.

**Comment by opoudjis** [comment]
This was a Heisenbug alright.

In isodoc postprocessing, I need to convert the HTML output into Nokogiri XHTML, in order to paste in the extraneous matter such as cover pages and stylesheets without incident. This has already meant that I have to clean up the Word HTML of coverpages to be accepted.

`<` in AsciiMath is being saved to XML as `&lt;`, a named entity. So the XHTML is processing named entities as found.

The `<` in the `&lt;` and other named entities are not accepted in XHTML by default. For whatever reason, we are not seeing those named entities break things when there is no appendix + bibliography. But we are when they are both enabled.

Rather than work out why this Heisenbug is happening, I'm removing all sources of the error: I am globally replacing named entities in the HTML being processed with hex entities, before converting it in Nokogiri XHTML. This seems to address this issue.
