### ISSUE TITLE
Two section titles are not rendering

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-itu#39]
1. The bibliography section title isn't rendering well when the bibliography environment is present.
2. The Abbreviations section title ("Abbreviations") isn't rendering well when the appendix environment is present. (If the text of the title is changed to something else, it renders just fine. So, apparently, the problem has to be exclusively with the word "Abbreviations".)

I attach relevant sample for demonstration purposes: [st-issue.zip](https://github.com/metanorma/metanorma-itu/files/3691209/st-issue.zip)

**Comment by opoudjis** [comment]
* Fixed by applying ticket https://github.com/metanorma/isodoc/issues/123 to ITU (had forgotten to), and generalising it to terms and definitions sections as well.

Note that you have an error in your sample document: the Abbreviations must not be a subsection of the references, but a sibling (so remove one initial =).

**Comment by opoudjis** [comment]
Fix will become available after https://github.com/metanorma/metanorma-itu/pull/45 is resolved.
