### ISSUE TITLE
README examples for :doctype: attribute mention IETF, is that a typo?

### ISSUE THREAD

**Issue by strogonoff** [metanorma/metanorma-itu#4]
Title self-explanatory.

**Comment by ronaldtse** [comment]
Sounds like an error? Can @opoudjis verify? Thanks!

**Comment by opoudjis** [comment]
@strogonoff, please assign me any queries around documentation, Ronald keeps overwhelming me with work, so I'm not going to notice mentions. Yes, it's an error, will fix.

**Comment by ronaldtse** [comment]
Thanks guys! 😄

**Comment by opoudjis** [comment]
Issue remains, and now it is a question for @ronaldtse: what are the permitted document types for ITU? https://www.itu.int/en/publications/Pages/default.aspx implies a couple of dozen types under "PUBLICATIONS BY SECTOR"; I hope that's not the case!

**Comment by ronaldtse** [comment]
@opoudjis the issue is about the "IETF" doctype? 

In any case, we're not going to deal with all ITU publications -- only Recommendations for now. ITU-T, ITU-R and ITU-D all provide Recommendations, but it's mainly ITU-T, and ITU-R.

The other doctype we will want to support is the Operational Bulletin from ITU, which is managed by ITU-T Study Group 2.

e.g.
* Word: https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-OB.1167-2019-OAS-MSW-E.docx
* PDF: https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-OB.1167-2019-OAS-PDF-E.pdf 

So only two `doctype`s.

**Comment by opoudjis** [comment]
Document types specified to date in the information model have been implemented, and documented in metanorma.com documentation (pending publication). At this time, nothing more to action.
