### ISSUE TITLE
Appendix appearance in ToC

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#65]
Table of Contents: there is no dash after "Appendix I" and "Appendix II", before the titles of appendices, as in referent .doc.

[toc_appendix_appearance.zip](https://github.com/metanorma/metanorma-itu/files/3726014/toc_appendix_appearance.zip)

**Comment by opoudjis** [comment]
Can't fix.

If the table of contents is automatically generated, as ours is, then it takes the header text it is indexing, and at most, strips line breaks. Otherwise, the titles in the table of contents replicate exactly the tables within the text. You get what you're seeing currently.

The Y.3507 is *manually typed in*. Because it is manually typed in, the editor can feel free to change the header text, e.g. by introducing dashes. But no automated table of contents is going to introduce characters that are absent from the source header. We cannot replicate this, so we will not.
