### ISSUE TITLE
Spacing in ToC

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#66]
Table of Contents: space is used between numbers and titles, while tab is used in referent .doc.

[spacing_toc.zip](https://github.com/metanorma/metanorma-itu/files/3726036/spacing_toc.zip)

**Comment by opoudjis** [comment]
This should have been fixed in the recent stylesheet update but wasn't, because for whatever reason the original stylesheet is expecting one more tab than what is actually inserted by Word.

If you update the table of contents (with a right click, update field), and load the stylesheet updated with this ticket, this should now work.
